[project]
name = "dmat-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.0",
    "fastapi>=0.141.1",
    "psycopg2>=2.9.12",
    "pylint>=4.0.6",
    "sqlalchemy>=2.0.51",
    "uvicorn[standard]>=0.52.1",
]

[dependency-groups]
dev = [
    "pylint>=4.0.6",
    "pyright>=1.1.411",
]
