### Create Mathematical Equation - Low
@baseUrl = http://localhost:8000
@storage = ~/repos/dMAT-Engine/app/storage/

POST {{baseUrl}}/api/questions
Content-Type: application/json

{
  "module_type": "mathematical_equations",
  "difficulty": "low",
  "data": {
    "equations": [
      "7 + A = 14",
      "B - 3 = A"
    ],
    "variables": ["A", "B"]
  },
  "solution": {
  "answers":{
    "A": 7,
    "B": 10
    }
  }
}

### Create Mathematical Equation - Medium
POST {{baseUrl}}/api/questions
Content-Type: application/json

{
  "module_type": "mathematical_equations",
  "difficulty": "medium",
  "data": {
    "equations": [
      "3 × C = A",
      "A + C = 8",
      "2 × A + 2 × C = B"
    ],
    "variables": ["A", "B", "C"]
  },
  "solution": {
  "answers":{
    "A": 6,
    "B": 16,
    "C": 2
    }
  }
}


### Create Mathematical Equation - High
POST {{baseUrl}}/api/questions
Content-Type: application/json

{
  "module_type": "mathematical_equations",
  "difficulty": "high",
  "data": {
    "equations": [
      "C + D - A = 1",
      "5 × C = D",
      "13 - C = A",
      "3 × C - 1 = B"
    ],
    "variables": ["A", "B", "C", "D"]
  },
  "solution": {
  "answers":{
    "A": 11,
    "B": 5,
    "C": 2,
    "D": 10
    }
  }
}


### Create Latin Square
POST {{baseUrl}}/api/questions
Content-Type: application/json

{
  "module_type": "latin_squares",
  "difficulty": "low",
  "data": {
    "grid": [
      ["B", "?", "A", "D", "E"],
      ["A", "B", "E", "C", "D"],
      ["C", "D", "B", "E", "A"],
      ["D", "E", "C", "A", "B"],
      ["E", "A", "D", "B", "C"]
    ],
    "symbols": ["A", "B", "C", "D", "E"],
    "question_mark": {
      "row": 0,
      "column": 1
    },
    "response_options": ["A", "B", "C", "D", "E"]
  },
  "solution": {
    "answer": "C"
  }
}

### Get Question
GET {{baseUrl}}/api/questions/1

### Get Question
GET {{baseUrl}}/api/questions/2

### Randome bug testings
GET {{baseUrl}}/api/questions/99999


### Create Figure Sequence
POST {{baseUrl}}/api/questions
Content-Type: application/json

{
  "module_type": "figure_sequences",
  "difficulty": "medium",
  "data": {
    "sequence": [
      {"position": 1, "asset_id": null},
      {"position": 2, "asset_id": null},
      {"position": 3, "asset_id": null},
      {"position": 4, "asset_id": null},
      {"position": 5, "asset_id": null},
      {"position": 6, "asset_id": null}
    ],
    "options": [
      {"position": 1, "asset_id": null},
      {"position": 2, "asset_id": null},
      {"position": 3, "asset_id": null},
      {"position": 4, "asset_id": null},
      {"position": 5, "asset_id": null},
      {"position": 6, "asset_id": null}
    ]
  },
  "solution": {
    "answers": {
      "5": "C",
      "6": "E"
    }
  }
}

### Figure 1
POST {{baseUrl}}/api/questions/5/assets

file=@storage/figure1.png
role=sequence
position=1



###TODO: Update the post api for assets and test it 
