"""Create foreign key in assets

Revision ID: bb40e567d2e8
Revises: cf083f4315b3
Create Date: 2026-08-12 10:33:24.141712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb40e567d2e8'
down_revision: Union[str, Sequence[str], None] = 'cf083f4315b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('question_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'assets', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'question_id')
    # ### end Alembic commands ###
